DSND-2385: POM updates and exclusions
companieshouse/filing-history-data-api pull request #14
Opened 2024-02-02 13:09 UTC by johncook-ch

## Describe the changes

Moved the dependencies to be exclusions rather than specific imports

Related Jira tickets
[DSND-2385](https://companieshouse.atlassian.net/browse/DSND-2385)

## Developer check list

### General

- [ ] Is the PR as small as it can be?
- [ ] Has the Jira ticket been updated with any relevant comments?
- [ ] Is the `README` up to date?
- [ ] Has the `POM` been updated for the latest versions of dependencies?
- [ ] Has the code been double-checked against `main`?
- [ ] Does the code adhere standards in this repository, including SonarQube checks?

### Testing

- [ ] Do the code changes have unit and integration tests with code coverage > 80%?
- [ ] Has the code been tested locally and/or passed the API Karate tests on Tilt?
- [ ] Have mandatory manual test cases been run?
- [ ] Are extra Karate tests required?
- [ ] Are all the test data resources up to date?

### Release preparation

_Where possible, add links to the respective Jira tickets when an item is checked_

- [ ] Have these changes been included in a release ticket?
- [ ] Are changes required to the `docker-chs-development` deployment or test data?
- [ ] Are any changes required to the environment added to deployment repositories?

## Notes to the tester

_Add any testing hints or instructions here._

2024-02-02 13:14 UTC, sthompsonCH approved these changes

2024-02-02 13:28 UTC, ch-code-analysis commented
CI: No security warnings found

2024-02-02 16:15 UTC, cgregoryCH requested changes

2024-02-02 16:15 UTC, cgregoryCH commented on pom.xml
>      <logback.version>1.4.14</logback.version>
Logback and jackson databind version properties can go too

2024-02-05 16:51 UTC, cgregoryCH approved these changes

2024-02-05 16:53 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-02-05 17:13 UTC, merged