DSND-2747: Improve performance of get list query
companieshouse/filing-history-data-api pull request #80
Opened 2024-08-07 15:02 UTC by crowlandsCH

## Describe the changes
* Get list  3 separate repository calls similar to this PR by Chris here https://github.com/companieshouse/company-appointments.api.ch.gov.uk/pull/169
* Finds a list of filing history document _id’s dependent on items per page, start index and category (if present) sorted descending on data.date. 
* Retrieves a list of FH documents to be present in the GET response using the list of id’s (preserving the sort order using a __sort_order__ field constructed on the fly to index the items in the filing history document list). 
* A final query to calculate the total_count of documents in the database matching the request sent.
* Various import and sonarlint issues fixed.

### Related Jira tickets

[DSND-2747](https://companieshouse.atlassian.net/browse/DSND-2747)

## Developer check list

### General

- [ ] Is the PR as small as it can be?
- [ ] Has the Jira ticket been updated with any relevant comments?
- [ ] Is the `README` up to date?
- [ ] Has the `POM` been updated for the latest versions of dependencies?
- [ ] Has the code been double-checked against `main`?
- [ ] Does the code adhere standards in this repository, including SonarQube checks?

### Testing

- [ ] Do the code changes have unit and integration tests with code coverage > 80%?
- [ ] Has the code been tested locally and/or passed the API Karate tests on Tilt?
- [ ] Have mandatory manual test cases been run?
- [ ] Are extra Karate tests required?
- [ ] Are all the test data resources up to date?

### Release preparation

_Where possible, add links to the respective Jira tickets when an item is checked_

- [ ] Have these changes been included in a release ticket?
- [ ] Are changes required to the `docker-chs-development` deployment or test data?
- [ ] Are any changes required to the environment added to deployment repositories?

## Notes to the tester

_Add any testing hints or instructions here._

2024-08-07 15:13 UTC, ch-code-analysis commented
CI: No security warnings found

2024-08-08 10:35 UTC, cgregoryCH requested changes

2024-08-08 10:35 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/filinghistory/api/repository/Repository.java
> +                    facet(match(new Criteria()), sort(Direction.DESC, "data.date")).as("ids"),
the match stage can be removed

2024-08-08 10:35 UTC, cgregoryCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/repository/RepositoryTest.java
> +        when(mongoTemplate.count(any(), eq(FilingHistoryDocument.class))).thenReturn(Long.valueOf(1));
```Long.valueOf(1)``` can be replaced with ```1L```

2024-08-08 10:35 UTC, cgregoryCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/repository/RepositoryTest.java
> +        when(mongoTemplate.count(any(), eq(FilingHistoryDocument.class))).thenReturn(Long.valueOf(1));
Same here

2024-08-08 10:35 UTC, cgregoryCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryServiceTest.java
> +        when(repository.countTotal(any(), any())).thenReturn(Long.valueOf(1));
Same here

2024-08-08 10:35 UTC, cgregoryCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryServiceTest.java
> +        when(repository.countTotal(any(), any())).thenReturn(Long.valueOf(0));
Same here

2024-08-08 10:35 UTC, cgregoryCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/repository/RepositoryTest.java
> +    void shouldCallMongoTemplateSuccessfullyWithCompanyNumberCriteriaOnly() {
These tests are testing too much. There should be one repository method called per test which tests a specific part of that method. Single responsibility should apply to source code and unit tests.

2024-08-08 10:56 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/filinghistory/api/repository/Repository.java
> +    public FilingHistoryIds findListOfFilingHistoryIds(String companyNumber,
done

2024-08-08 10:56 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/filinghistory/api/repository/Repository.java
> +                    facet(match(new Criteria()), sort(Direction.DESC, "data.date")).as("ids"),
done

2024-08-08 10:59 UTC, crowlandsCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/repository/RepositoryTest.java
> +        when(mongoTemplate.count(any(), eq(FilingHistoryDocument.class))).thenReturn(Long.valueOf(1));
done

2024-08-08 10:59 UTC, crowlandsCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryServiceTest.java
> +        when(repository.countTotal(any(), any())).thenReturn(Long.valueOf(1));
done

2024-08-08 10:59 UTC, crowlandsCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/service/FilingHistoryServiceTest.java
> +        when(repository.countTotal(any(), any())).thenReturn(Long.valueOf(0));
done

2024-08-08 11:00 UTC, crowlandsCH commented on src/test/java/uk/gov/companieshouse/filinghistory/api/repository/RepositoryTest.java
> +        when(mongoTemplate.count(any(), eq(FilingHistoryDocument.class))).thenReturn(Long.valueOf(1));
done

2024-08-08 11:21 UTC, ch-code-analysis commented
CI: No security warnings found

2024-08-08 12:24 UTC, ch-code-analysis commented
CI: No security warnings found

2024-08-08 12:41 UTC, cgregoryCH approved these changes

2024-08-08 12:51 UTC, johncook-ch approved these changes

2024-08-08 13:33 UTC, merged